printers:
  - printerId: 99
    outletId: 1
    name: Test
    #iPAddress: 10.0.0.3
    iPAddress: 192.168.1.113
    isUsbPrinter: false
    lineCharacters: 56
  # - printerId: 123
  #   name: Usb Printer
  #   filePath: /dev/usb/lp0
  #   isUsbPrinter: true
